/**
 * Nesse arquivo foi inserido todas as constantes de mensagens, validações e códigos de retornos
 * para as operações.
 */

const ENTITIES = {
    PRODUCT_TYPE: 'product_type',
    PRODUCT: 'product',
    STOCK: 'stock',
    PURCHASE: 'purchase',
    ITEM_PURCHASE: 'item_purchase',
    PERSON: 'person'
}

const NAME_ENTITIES = {
    PRODUCT_TYPE: 'Tipo de Produto',
    PRODUCT: 'Produto',
    STOCK: 'Estoque',
    PURCHASE: 'Compra',
    ITEM_PURCHASE: 'Item de Compra',
    PERSON: 'Pessoa'
}

const SHORT_MESSAGES = {
    NOT_FOUND: 'Não foi localizado',
    SUCCESS: 'Sucesso',
    CREATE_SUCCESS: 'Criado com sucesso!',
    EDIT_SUCCESS: 'Editado com sucesso!',
    DELETE_SUCESS: 'Removido com sucesso!',
    ERROR: 'Erro',
    VALIDATION_ERROR: 'Erro de validação:',
    PARAMETER_NOT_INFORMED: 'Parâmetro não informado',
}

const VALIDATIONS = {
    COLUMN_BLANK: 'Campo está vazio',
    ZERO_OR_NULL: 'Informado valor zerado ou vazio',
    NEGATIVE: 'Informado valor negativo',
    IN_ANOTHER_ENTITY: 'Vinculado na entidade',
    DELETE_NOT_PERMITED: 'Não é permitido realizar a exclusão.',
    CANNOT_INSERT_PRODUCT_EXIST: 'para o Produto, já existe',
    NOT_EDITABLE: 'não é possível editar, pois está vinculado ao'
}

const MESSAGES = {
    PRODUCT_TYPE_NOT_FOUND: NAME_ENTITIES.PRODUCT_TYPE.concat(' ', SHORT_MESSAGES.NOT_FOUND),
    PRODUCT_TYPE_CREATE_SUCCESS: NAME_ENTITIES.PRODUCT_TYPE.concat(' ', SHORT_MESSAGES.CREATE_SUCCESS),
    PRODUCT_TYPE_EDIT_SUCCESS: NAME_ENTITIES.PRODUCT_TYPE.concat(' ', SHORT_MESSAGES.EDIT_SUCCESS),
    PRODUCT_TYPE_DELETE_SUCCESS: NAME_ENTITIES.PRODUCT_TYPE.concat(' ', SHORT_MESSAGES.DELETE_SUCESS),
    PRODUCT_TYPE_IN_PRODUCT: VALIDATIONS.DELETE_NOT_PERMITED.concat(' ', NAME_ENTITIES.PRODUCT_TYPE, ' ', VALIDATIONS.IN_ANOTHER_ENTITY, ' ', NAME_ENTITIES.PRODUCT),
    PRODUCT_NOT_FOUND: NAME_ENTITIES.PRODUCT.concat(' ', SHORT_MESSAGES.NOT_FOUND),
    PRODUCT_CREATE_SUCCESS: NAME_ENTITIES.PRODUCT.concat(' ', SHORT_MESSAGES.CREATE_SUCCESS),
    PRODUCT_EDIT_SUCCESS: NAME_ENTITIES.PRODUCT.concat(' ', SHORT_MESSAGES.EDIT_SUCCESS),
    PRODUCT_DELETE_SUCCESS: NAME_ENTITIES.PRODUCT.concat(' ', SHORT_MESSAGES.DELETE_SUCESS),
    STOCK_NOT_FOUND: NAME_ENTITIES.STOCK.concat(' ', SHORT_MESSAGES.NOT_FOUND),
    STOCK_CREATE_SUCCESS: NAME_ENTITIES.STOCK.concat(' ', SHORT_MESSAGES.CREATE_SUCCESS),
    STOCK_EDIT_SUCCESS: NAME_ENTITIES.STOCK.concat(' ', SHORT_MESSAGES.EDIT_SUCCESS),
    STOCK_DELETE_SUCCESS: NAME_ENTITIES.STOCK.concat(' ', SHORT_MESSAGES.DELETE_SUCESS),
    STOCK_EXIST: NAME_ENTITIES.STOCK.concat(' ', VALIDATIONS.CANNOT_INSERT_PRODUCT_EXIST),
    STOCK_PRODUCT_NOT_EDITABLE: NAME_ENTITIES.STOCK.concat(' ', VALIDATIONS.NOT_EDITABLE, ' ', NAME_ENTITIES.PRODUCT),
    PURCHASE_NOT_FOUND: NAME_ENTITIES.PURCHASE.concat(' ', SHORT_MESSAGES.NOT_FOUND),
    PURCHASE_CREATE_SUCCESS: NAME_ENTITIES.PURCHASE.concat(' ', SHORT_MESSAGES.CREATE_SUCCESS),
    PURCHASE_EDIT_SUCCESS: NAME_ENTITIES.PURCHASE.concat(' ', SHORT_MESSAGES.EDIT_SUCCESS),
    PURCHASE_DELETE_SUCCESS: NAME_ENTITIES.PURCHASE.concat(' ', SHORT_MESSAGES.DELETE_SUCESS),
    ITEM_PURCHASE_NOT_FOUND: NAME_ENTITIES.ITEM_PURCHASE.concat(' ', SHORT_MESSAGES.NOT_FOUND),
    ITEM_PURCHASE_CREATE_SUCCESS: NAME_ENTITIES.ITEM_PURCHASE.concat(' ', SHORT_MESSAGES.CREATE_SUCCESS),
    ITEM_PURCHASE_EDIT_SUCCESS: NAME_ENTITIES.ITEM_PURCHASE.concat(' ', SHORT_MESSAGES.EDIT_SUCCESS),
    ITEM_PURCHASE_DELETE_SUCCESS: NAME_ENTITIES.ITEM_PURCHASE.concat(' ', SHORT_MESSAGES.DELETE_SUCESS),
    ITEM_PURCHASE_PURCHASE_NOT_EDITABLE: NAME_ENTITIES.ITEM_PURCHASE.concat(' ', VALIDATIONS.NOT_EDITABLE, ' ', NAME_ENTITIES.PURCHASE),
    PERSON_NOT_FOUND: NAME_ENTITIES.PERSON.concat(' ', SHORT_MESSAGES.NOT_FOUND),
    PERSON_CREATE_SUCCESS: NAME_ENTITIES.PERSON.concat(' ', SHORT_MESSAGES.CREATE_SUCCESS),
    PERSON_EDIT_SUCCESS: NAME_ENTITIES.PERSON.concat(' ', SHORT_MESSAGES.EDIT_SUCCESS),
    PERSON_DELETE_SUCCESS: NAME_ENTITIES.PERSON.concat(' ', SHORT_MESSAGES.DELETE_SUCESS),
}

const RETURN_CODES = {
    INTERNAL_SERVER_ERROR: 500,
    BAD_REQUEST: 400,
    NOT_FOUND: 404,
    CREATED: 201,
    SUCCESS: 200
};

module.exports = {
    ENTITIES,
    NAME_ENTITIES,
    SHORT_MESSAGES,
    MESSAGES,
    RETURN_CODES,
    VALIDATIONS
}